/**
 * imageSections.js — single source of truth for every managed image on the site.
 *
 * Section types:
 *   'single'   — one image; large preview in admin, replace button
 *   'gallery'  — variable count; free add / remove / reorder
 *   'carousel' — fixed named slots (one image per slide); replace only
 *   'cards'    — fixed named slots (one image per card); replace only
 *
 * All sections are stored in Firestore collection: site_images
 * Document ID = section id.
 */

export const SECTIONS = [
  // ─── HOME PAGE ─────────────────────────────────────────────────────────────
  {
    id: 'home-gallery',
    page: 'home',
    name: 'Hero Gallery Slideshow',
    hint: 'Rotating photo carousel at the very top of the home page',
    type: 'gallery',
    images: [
      { id: 'g1',  url: '/assets/images/facility/hq-0745.jpg',                        alt: 'HQ Aviation hangar' },
      { id: 'g2',  url: '/assets/images/gallery/events/img_2644.jpeg',                alt: 'HQ Aviation event' },
      { id: 'g3',  url: '/assets/images/facility/hq-0354.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g4',  url: '/assets/images/facility/hq-0254.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g5',  url: '/assets/images/facility/hq-0035.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g6',  url: '/assets/images/facility/hq-0089.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g7',  url: '/assets/images/facility/hq-0696.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g8',  url: '/assets/images/facility/hq-0409.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g9',  url: '/assets/images/facility/hq-0167.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g10', url: '/assets/images/facility/hq-0698.jpg',                        alt: 'HQ Aviation facility' },
      { id: 'g11', url: '/assets/images/gallery/flying/flying--1.jpg',                alt: 'Helicopter in flight' },
      { id: 'g12', url: '/assets/images/gallery/carousel/rotating1.jpg',              alt: 'HQ Aviation helicopter' },
      { id: 'g13', url: '/assets/images/gallery/carousel/rotating6.jpg',              alt: 'HQ Aviation helicopter' },
      { id: 'g14', url: '/assets/images/training/home-2312.jpg',                      alt: 'HQ Aviation training' },
      { id: 'g15', url: '/assets/images/gallery/carousel/rotating-3.jpg',             alt: 'HQ Aviation helicopter' },
      { id: 'g16', url: '/assets/images/legacy/dated/2015-04-09-16.29.34.jpg',        alt: 'HQ Aviation archive' },
      { id: 'g17', url: '/assets/images/used-aircraft/r66/gdspz.jpg',                 alt: 'Robinson R66' },
    ],
  },
  {
    id: 'home-flying-bg',
    page: 'home',
    name: 'Flying Section Background',
    hint: 'Full-width background image behind the "FLYING" parallax section',
    type: 'single',
    images: [
      { id: 's1', url: '/assets/images/gallery/flying/flying-.jpg', alt: 'HQ Aviation helicopter flying' },
    ],
  },
  {
    id: 'home-training-carousel',
    page: 'home',
    name: 'Training Carousel',
    hint: 'One image per training course tab — Discovery Flight, PPL, CPL, etc.',
    type: 'carousel',
    slideLabels: ['Discovery Flight', 'Private Pilot Licence', 'Commercial Pilot Licence', 'Type Rating', 'Night Rating', 'Self-Fly Hire'],
    images: [
      { id: 't1', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Discovery flight experience' },
      { id: 't2', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Private pilot licence training' },
      { id: 't3', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Commercial pilot licence training' },
      { id: 't4', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Type rating training' },
      { id: 't5', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Night rating training' },
      { id: 't6', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Self-fly hire' },
    ],
  },
  {
    id: 'home-maintenance-bg',
    page: 'home',
    name: 'Maintenance Section Background',
    hint: 'Full-width background image behind the "MAINTENANCE" parallax section',
    type: 'single',
    images: [
      { id: 's2', url: '/assets/images/facility/maintenance-.jpg', alt: 'HQ Aviation maintenance facility' },
    ],
  },
  {
    id: 'home-maintenance-carousel',
    page: 'home',
    name: 'Maintenance Carousel',
    hint: 'One image per maintenance service tab — Rebuilds, Maintenance, Part Sales, etc.',
    type: 'carousel',
    slideLabels: ['Rebuilds', 'Maintenance', 'Part Sales', 'Hangarage', 'Avionics'],
    images: [
      { id: 'm1', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Helicopter rebuilds' },
      { id: 'm2', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Helicopter maintenance' },
      { id: 'm3', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Helicopter parts' },
      { id: 'm4', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Aircraft hangarage' },
      { id: 'm5', url: '/assets/images/gallery/carousel/rotating-4.jpg', alt: 'Helicopter avionics' },
    ],
  },
  {
    id: 'home-sales-bg',
    page: 'home',
    name: 'Sales Section Background',
    hint: 'Full-width background image behind the "Sales" parallax section',
    type: 'single',
    images: [
      { id: 's3', url: '/assets/images/facility/main-sales-pic.jpg', alt: 'HQ Aviation aircraft sales' },
    ],
  },
  {
    id: 'home-sales-carousel',
    page: 'home',
    name: 'Sales Carousel',
    hint: 'One image per sales tab — New Helicopters, Used Helicopters, Rebuilt Helicopters',
    type: 'carousel',
    slideLabels: ['New Helicopters', 'Used Helicopters', 'Rebuilt Helicopters'],
    images: [
      { id: 'sl1', url: '/assets/images/legacy/squarespace/image-asset.jpeg',   alt: 'New helicopters for sale' },
      { id: 'sl2', url: '/assets/images/legacy/squarespace/image-asset-1.jpeg', alt: 'Used helicopters for sale' },
      { id: 'sl3', url: '/assets/images/facility/sales-rebuild.jpg',             alt: 'Rebuilt helicopters for sale' },
    ],
  },

  // ─── TRAINING PAGE ─────────────────────────────────────────────────────────
  {
    id: 'training-intro',
    page: 'training',
    name: 'Training Introduction Image',
    hint: 'Photo next to the opening paragraph on the training page',
    type: 'single',
    images: [
      { id: 's4', url: '/assets/images/training/helicopter-training.webp', alt: 'Helicopter flight training at HQ Aviation' },
    ],
  },
  {
    id: 'training-trial-lesson',
    page: 'training',
    name: 'Trial Lesson Image',
    hint: 'Photo in the "What is a Trial Lesson?" section',
    type: 'single',
    images: [
      { id: 's5', url: '/assets/images/training/trial-lesson.webp', alt: 'Trial helicopter lesson' },
    ],
  },

  // ─── MAINTENANCE PAGE ──────────────────────────────────────────────────────
  {
    id: 'maintenance-facility',
    page: 'maintenance',
    name: 'Maintenance Facility Photo',
    hint: 'Hangar photo next to the opening paragraph on the maintenance page',
    type: 'single',
    images: [
      { id: 's6', url: '/assets/images/facility/hq-aviation-helicopter-hangar.webp', alt: 'HQ Aviation maintenance hangar' },
    ],
  },
  {
    id: 'maintenance-overhaul',
    page: 'maintenance',
    name: 'Overhaul Photo',
    hint: 'Robinson overhaul photo in the certifications section',
    type: 'single',
    images: [
      { id: 's7', url: '/assets/images/facility/g-ccfc-hq-robinson-overhaul.webp', alt: 'Robinson helicopter overhaul at HQ Aviation' },
    ],
  },
  {
    id: 'maintenance-cert-logo',
    page: 'maintenance',
    name: 'Robinson Authorised Logo',
    hint: 'Certification badge shown in the authorised service centre section',
    type: 'single',
    images: [
      { id: 's8', url: '/assets/images/logos/certifications/robinson-authorized.jpg', alt: 'Robinson Authorized Service Centre' },
    ],
  },
  {
    id: 'maintenance-aircraft',
    page: 'maintenance',
    name: 'Supported Aircraft Models',
    hint: 'One image per aircraft card — R22, R44, R66, Cabri G2',
    type: 'cards',
    slideLabels: ['Robinson R22', 'Robinson R44', 'Robinson R66', 'Guimbal Cabri G2'],
    images: [
      { id: 'a1', url: '/assets/images/new-aircraft/r22-beta.webp',    alt: 'Robinson R22 Beta' },
      { id: 'a2', url: '/assets/images/new-aircraft/r44-raven.webp',   alt: 'Robinson R44 Raven' },
      { id: 'a3', url: '/assets/images/new-aircraft/r66-turbine.webp', alt: 'Robinson R66 Turbine' },
      { id: 'a4', url: '/assets/images/new-aircraft/cabri-g2.webp',    alt: 'Guimbal Cabri G2' },
    ],
  },

  // ─── EXPEDITIONS PAGE ──────────────────────────────────────────────────────
  {
    id: 'expeditions-cards',
    page: 'expeditions',
    name: 'Expedition Destination Cards',
    hint: 'One image per destination card — Scottish Highlands, Norwegian Fjords, etc.',
    type: 'cards',
    slideLabels: ['Scottish Highlands', 'Norwegian Fjords', 'Moroccan Atlas', 'Swiss Alps'],
    images: [
      { id: 'e1', url: '/assets/images/expeditions/scottish-highlands.webp', alt: 'Scottish Highlands helicopter expedition' },
      { id: 'e2', url: '/assets/images/expeditions/norwegian-fjords.webp',   alt: 'Norwegian Fjords helicopter expedition' },
      { id: 'e3', url: '/assets/images/expeditions/moroccan-atlas.webp',     alt: 'Moroccan Atlas helicopter expedition' },
      { id: 'e4', url: '/assets/images/expeditions/swiss-alps.webp',         alt: 'Swiss Alps helicopter expedition' },
    ],
  },
  {
    id: 'expeditions-bespoke',
    page: 'expeditions',
    name: 'Bespoke Adventures Image',
    hint: 'Photo next to the bespoke adventures section',
    type: 'single',
    images: [
      { id: 's9', url: '/assets/images/expeditions/bespoke-adventure.webp', alt: 'Bespoke helicopter adventure' },
    ],
  },
  {
    id: 'expeditions-captain',
    page: 'expeditions',
    name: 'Captain Q Expedition Photo',
    hint: 'Captain Quentin Smith photo in the "Your Guide" section',
    type: 'single',
    images: [
      { id: 's10', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp', alt: 'Captain Q on helicopter expedition' },
    ],
  },

  // ─── HOME PAGE (real homepage — Experimentation.jsx at /) ─────────────────
  // These sections are wired to the actual live homepage, not /home.
  {
    id: 'home-hero-slides',
    page: 'home',
    name: 'Hero — Background Slides',
    hint: 'The 3 background images that cycle behind the hero headline',
    type: 'carousel',
    viewport: 'desktop',
    slideLabels: ['Slide 1', 'Slide 2', 'Slide 3'],
    images: [
      { id: 'hs1', url: '/assets/images/facility/hq-0209.jpg',               alt: 'HQ Aviation facility' },
      { id: 'hs2', url: '/assets/images/facility/hq-0056.jpg',               alt: 'HQ Aviation facility' },
      { id: 'hs3', url: '/assets/images/gallery/carousel/rotating6.jpg',     alt: 'HQ Aviation helicopter' },
    ],
  },
  {
    id: 'home-editorial-strip-1',
    page: 'home',
    name: 'Photo Strip — Row 1',
    hint: 'Horizontal scrolling photo strip (top row) below the hero section',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'ep1',  url: '/assets/images/expeditions/antartica.jpg',                                        alt: 'Antarctica expedition' },
      { id: 'ep2',  url: '/assets/images/gallery/flying/flying-.jpg',                                       alt: 'Helicopter flying' },
      { id: 'ep3',  url: '/assets/images/expeditions/channel.jpg',                                          alt: 'Channel crossing' },
      { id: 'ep4',  url: '/assets/images/facility/hq-aviation-robinsons.jpg',                               alt: 'HQ Aviation fleet' },
      { id: 'ep5',  url: '/assets/images/expeditions/north-pole.jpg',                                       alt: 'North Pole expedition' },
      { id: 'ep6',  url: '/assets/images/gallery/flying/foggy-evening-flying.jpg',                         alt: 'Evening flight' },
      { id: 'ep7',  url: '/assets/images/facility/main-sales-pic.jpg',                                      alt: 'HQ Aviation showroom' },
      { id: 'ep8',  url: '/assets/images/facility/busy-hangar.jpg',                                         alt: 'Busy hangar' },
      { id: 'ep9',  url: '/assets/images/new-aircraft/r88/rhc-r88-left-side-three-quarter-front-view-21797.jpg', alt: 'R88 helicopter' },
      { id: 'ep10', url: '/assets/images/facility/hq-0696.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep11', url: '/assets/images/new-aircraft/r88/rhc-r88-atmospheric-effect-front-view-218022.jpg', alt: 'R88 atmospheric' },
      { id: 'ep12', url: '/assets/images/facility/hq-0345.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep13', url: '/assets/images/facility/hq-0153.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep14', url: '/assets/images/facility/hq-0254.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep15', url: '/assets/images/gallery/flying/flying--1.jpg',                                    alt: 'Helicopter in flight' },
      { id: 'ep16', url: '/assets/images/facility/hq-0391.jpg',                                             alt: 'Engineering workshop' },
      { id: 'ep17', url: '/assets/images/facility/hq-0502.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep18', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                         alt: 'Six helicopters at North Pole' },
      { id: 'ep19', url: '/assets/images/facility/hq-0209.jpg',                                             alt: 'HQ Aviation facility' },
      { id: 'ep20', url: '/assets/images/facility/okey-paint-quality.jpg',                                  alt: 'Paint quality' },
    ],
  },
  {
    id: 'home-editorial-strip-2',
    page: 'home',
    name: 'Photo Strip — Row 2',
    hint: 'Horizontal scrolling photo strip (bottom row) below the hero section',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'eq1',  url: '/assets/images/facility/hq-0035.jpg',                               alt: 'Hangar floor' },
      { id: 'eq2',  url: '/assets/images/facility/hq-0294.jpg',                               alt: 'HQ Aviation facility' },
      { id: 'eq3',  url: '/assets/images/gallery/flying/james-shadow-night.jpg',              alt: 'Night flying' },
      { id: 'eq4',  url: '/assets/images/facility/hq-0409.jpg',                               alt: 'HQ Aviation facility' },
      { id: 'eq5',  url: '/assets/images/facility/sales-rebuild.jpg',                         alt: 'Rebuild in progress' },
      { id: 'eq6',  url: '/assets/images/facility/hq-0477.jpg',                               alt: 'Engine work' },
      { id: 'eq7',  url: '/assets/images/gallery/flying/foggy-evening-flying.jpg',            alt: 'Evening flight' },
      { id: 'eq8',  url: '/assets/images/facility/hq-0745.jpg',                               alt: 'Aircraft on apron' },
      { id: 'eq9',  url: '/assets/images/facility/hq-0089.jpg',                               alt: 'Component detail' },
      { id: 'eq10', url: '/assets/images/facility/hq-0354.jpg',                               alt: 'Rotor inspection' },
      { id: 'eq11', url: '/assets/images/facility/hq-0153-1.jpg',                             alt: 'HQ Aviation facility' },
      { id: 'eq12', url: '/assets/images/facility/hq-0300.jpg',                               alt: 'Cockpit instruments' },
      { id: 'eq13', url: '/assets/images/facility/maintenance-.jpg',                          alt: 'Maintenance facility' },
      { id: 'eq14', url: '/assets/images/facility/hq-0075.jpg',                               alt: 'HQ Aviation facility' },
      { id: 'eq15', url: '/assets/images/facility/hq-img_1340.jpg',                           alt: 'HQ Aviation facility' },
      { id: 'eq16', url: '/assets/images/facility/hq-0698.jpg',                               alt: 'HQ Aviation facility' },
      { id: 'eq17', url: '/assets/images/facility/hq-0129.jpg',                               alt: 'HQ Aviation facility' },
      { id: 'eq18', url: '/assets/images/facility/hq-0167.jpg',                               alt: 'Avionics bench' },
      { id: 'eq19', url: '/assets/images/facility/hq-0053.jpg',                               alt: 'Workshop detail' },
      { id: 'eq20', url: '/assets/images/facility/hq-0388.jpg',                               alt: 'HQ Aviation facility' },
    ],
  },
  {
    id: 'home-facility-gallery',
    page: 'home',
    name: 'Maintenance Gallery',
    hint: 'Full-screen lightbox gallery in the maintenance section of the homepage',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'fg1',  url: '/assets/images/facility/maintenance-.jpg',          alt: 'Maintenance facility' },
      { id: 'fg2',  url: '/assets/images/facility/hq-0391.jpg',               alt: 'Engineering workshop' },
      { id: 'fg3',  url: '/assets/images/facility/hq-0477.jpg',               alt: 'Engine work' },
      { id: 'fg4',  url: '/assets/images/facility/hq-0354.jpg',               alt: 'Rotor inspection' },
      { id: 'fg5',  url: '/assets/images/facility/hq-0035.jpg',               alt: 'Hangar floor' },
      { id: 'fg6',  url: '/assets/images/facility/hq-0089.jpg',               alt: 'Component detail' },
      { id: 'fg7',  url: '/assets/images/facility/hq-0745.jpg',               alt: 'Aircraft on apron' },
      { id: 'fg8',  url: '/assets/images/facility/sales-rebuild.jpg',         alt: 'Rebuild in progress' },
      { id: 'fg9',  url: '/assets/images/facility/hq-0167.jpg',               alt: 'Avionics bench' },
      { id: 'fg10', url: '/assets/images/facility/okey-paint-quality.jpg',    alt: 'Paint shop' },
    ],
  },
  {
    id: 'home-training-tabs',
    page: 'home',
    name: 'Training Section — Tab Images',
    hint: 'One image per training tab on the homepage (Discovery Flight, PPL, Self-Fly Hire, CPL, Night Rating)',
    type: 'carousel',
    viewport: 'both',
    slideLabels: ['Discovery Flight', 'Private Pilot Licence', 'Self-Fly Hire', 'Commercial Pilot Licence', 'Night Rating', 'Type Rating', 'Tours of London'],
    images: [
      { id: 'ht1', url: '/assets/images/gallery/carousel/rotating1.jpg',              alt: 'Discovery flight experience' },
      { id: 'ht2', url: '/assets/images/gallery/carousel/rotating2.jpg',              alt: 'Private pilot licence training' },
      { id: 'ht3', url: '/assets/images/gallery/carousel/rotating8.jpg',              alt: 'Self-fly hire' },
      { id: 'ht4', url: '/assets/images/gallery/carousel/rotating-3.jpg',             alt: 'Commercial pilot licence' },
      { id: 'ht5', url: '/assets/images/gallery/carousel/rotating6.jpg',              alt: 'Night rating' },
      { id: 'ht6', url: '/assets/images/gallery/carousel/rotating-4.jpg',             alt: 'Type rating training' },
      { id: 'ht7', url: '/assets/images/lifestyle/london-battersea-heliport.jpg',     alt: 'London helicopter tours' },
    ],
  },

  // ─── HOME PAGE — ADDITIONAL SECTIONS ──────────────────────────────────────
  {
    id: 'home-hero-slides-mobile',
    page: 'home',
    name: 'Hero — Mobile Background Slides',
    hint: 'The 2 background images shown on phones behind the hero (different from desktop)',
    type: 'carousel',
    viewport: 'mobile',
    slideLabels: ['Mobile Slide 1', 'Mobile Slide 2'],
    images: [
      { id: 'hm1', url: '/assets/images/gallery/carousel/r22-london-mobile-hq.jpg', alt: 'R22 over London' },
      { id: 'hm2', url: '/assets/images/gallery/carousel/rotating6-mobile.jpg',     alt: 'HQ Aviation helicopter' },
    ],
  },
  {
    id: 'home-sfh-fleet',
    page: 'home',
    name: 'Self-Fly Hire — Fleet Images',
    hint: 'One aircraft image per fleet row in the Self-Fly Hire section (R66, R44, R22)',
    type: 'carousel',
    viewport: 'both',
    slideLabels: ['R66 Turbine', 'R44', 'R22'],
    images: [
      { id: 'sf1', url: '/assets/images/new-aircraft/r66/blue-r66-palo-verde-front-v4.png', alt: 'R66 Turbine' },
      { id: 'sf2', url: '/assets/images/new-aircraft/r44/raven-ii-front-alpha.png',          alt: 'R44' },
      { id: 'sf3', url: '/assets/images/new-aircraft/r22/r22-red-volcano-front-alpha-v3.png', alt: 'R22' },
    ],
  },
  {
    id: 'home-sfh-intro-img',
    page: 'home',
    name: 'Self-Fly Hire — Desktop Intro Carousel',
    hint: 'Auto-scrolling photo carousel on the left side of the Self-Fly Hire intro (desktop only). Add as many images as you like — they loop continuously.',
    type: 'gallery',
    viewport: 'desktop',
    images: [
      { id: 'si1', url: '/assets/images/facility/hq-0167.jpg',         alt: 'Helicopter on the pad' },
      { id: 'si2', url: '/assets/images/facility/fleet-lineup.jpg',    alt: 'Fleet lineup' },
      { id: 'si3', url: '/assets/images/facility/hq-0153-3.jpg',       alt: 'Helicopters on the airfield' },
      { id: 'si4', url: '/assets/images/gallery/flying/flying-.jpg',   alt: 'Flying' },
      { id: 'si5', url: '/assets/images/facility/hq-0696.jpg',         alt: 'Captain Q flying' },
      { id: 'si6', url: '/assets/images/facility/hq-0300.jpg',         alt: 'R66 cockpit instruments' },
      { id: 'si7', url: '/assets/images/facility/fleet-lineup-sunset.jpg', alt: 'Fleet at sunset' },
    ],
  },
  {
    id: 'home-sfh-mobile-carousel',
    page: 'home',
    name: 'Self-Fly Hire — Mobile Carousel',
    hint: 'Scrolling photo carousel shown on mobile in the Self-Fly Hire section',
    type: 'gallery',
    viewport: 'mobile',
    images: [
      { id: 'sm1', url: '/assets/images/facility/hq-0167.jpg',                    alt: 'Helicopter on the pad' },
      { id: 'sm2', url: '/assets/images/facility/fleet-lineup.jpg',               alt: 'Fleet lineup' },
      { id: 'sm3', url: '/assets/images/facility/hq-0153-3.jpg',                  alt: 'Helicopters on the airfield' },
      { id: 'sm4', url: '/assets/images/gallery/flying/flying-.jpg',              alt: 'Flying' },
      { id: 'sm5', url: '/assets/images/facility/hq-0696.jpg',                    alt: 'Captain Q flying' },
      { id: 'sm6', url: '/assets/images/facility/hq-0300.jpg',                    alt: 'R66 cockpit instruments' },
      { id: 'sm7', url: '/assets/images/facility/fleet-lineup-sunset.jpg',        alt: 'Fleet at sunset' },
    ],
  },
  {
    id: 'home-maint-scroll-1',
    page: 'home',
    name: 'Maintenance — Scroll Gallery Row 1',
    hint: 'Left column of the vertical-scrolling maintenance photo gallery (scrolls upward)',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'ms1', url: '/assets/images/facility/maintenance-.jpg',   alt: 'Maintenance facility' },
      { id: 'ms2', url: '/assets/images/facility/hq-0391.jpg',        alt: 'Engineering workshop' },
      { id: 'ms3', url: '/assets/images/facility/hq-0477.jpg',        alt: 'Engine work' },
      { id: 'ms4', url: '/assets/images/facility/hq-0354.jpg',        alt: 'Rotor inspection' },
      { id: 'ms5', url: '/assets/images/facility/hq-0035.jpg',        alt: 'Hangar floor' },
      { id: 'ms6', url: '/assets/images/facility/hq-0089.jpg',        alt: 'Component detail' },
      { id: 'ms7', url: '/assets/images/facility/hq-0745.jpg',        alt: 'Aircraft on apron' },
    ],
  },
  {
    id: 'home-maint-scroll-2',
    page: 'home',
    name: 'Maintenance — Scroll Gallery Row 2',
    hint: 'Right column of the vertical-scrolling maintenance photo gallery (scrolls downward)',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'mt1', url: '/assets/images/facility/sales-rebuild.jpg',      alt: 'Rebuild in progress' },
      { id: 'mt2', url: '/assets/images/facility/hq-0167.jpg',            alt: 'Avionics bench' },
      { id: 'mt3', url: '/assets/images/facility/okey-paint-quality.jpg', alt: 'Paint shop' },
      { id: 'mt4', url: '/assets/images/facility/hq-0345.jpg',            alt: 'Rotor blades' },
      { id: 'mt5', url: '/assets/images/facility/hq-0053.jpg',            alt: 'Workshop' },
      { id: 'mt6', url: '/assets/images/facility/hq-0300.jpg',            alt: 'Cockpit instruments' },
      { id: 'mt7', url: '/assets/images/facility/hq-0696.jpg',            alt: 'Aircraft on apron' },
    ],
  },
  {
    id: 'home-about-carousel',
    page: 'home',
    name: 'About — Founder Carousel',
    hint: 'Mobile-only carousel of Captain Q expedition photos in the About section',
    type: 'gallery',
    viewport: 'mobile',
    images: [
      { id: 'ac1', url: '/assets/images/expeditions/antartica.jpg',               alt: 'Antarctica expedition' },
      { id: 'ac2', url: '/assets/images/expeditions/north-pole.jpg',              alt: 'North Pole landing' },
      { id: 'ac3', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg', alt: 'Six helicopters at the North Pole' },
      { id: 'ac4', url: '/assets/images/expeditions/channel.jpg',                 alt: 'Channel crossing' },
      { id: 'ac5', url: '/assets/images/facility/hq-0696.jpg',                    alt: 'Captain Q flying' },
      { id: 'ac6', url: '/assets/images/gallery/flying/flying-.jpg',              alt: 'Helicopter in flight' },
    ],
  },
  {
    id: 'home-clubhouse-carousel',
    page: 'home',
    name: 'Clubhouse — Mobile Carousel',
    hint: 'Mobile-only carousel of clubhouse interior and detail photos',
    type: 'gallery',
    viewport: 'mobile',
    images: [
      { id: 'cc1', url: '/assets/images/facility/hq-0345.jpg',   alt: 'The clubhouse lounge' },
      { id: 'cc2', url: '/assets/images/facility/hq-0354.jpg',   alt: 'Globe on the clubhouse desk' },
      { id: 'cc3', url: '/assets/images/facility/hq-0053.jpg',   alt: 'Helmet light and framed photos' },
      { id: 'cc4', url: '/assets/images/facility/hq-0391.jpg',   alt: 'Captain Q expedition photo on the wall' },
      { id: 'cc5', url: '/assets/images/facility/hq-0477.jpg',   alt: 'Helicopter compass instrument' },
      { id: 'cc6', url: '/assets/images/facility/hq-0300.jpg',   alt: 'R66 Turbine cockpit instruments' },
      { id: 'cc7', url: '/assets/images/facility/hq-0388.jpg',   alt: "Air Pilot's Manual on vintage trunk" },
      { id: 'cc8', url: '/assets/images/facility/hq-0696.jpg',   alt: 'Captain Q flying' },
      { id: 'cc9', url: '/assets/images/facility/hq-0153-3.jpg', alt: 'Helicopters on the airfield' },
    ],
  },
  {
    id: 'home-sales-intro-gallery',
    page: 'home',
    name: 'Sales — Intro Photo Gallery',
    hint: 'Grid of facility/fleet photos at the top of the Sales section (desktop)',
    type: 'gallery',
    viewport: 'desktop',
    images: [
      { id: 'sg1',  url: '/assets/images/facility/main-sales-pic.jpg',        alt: 'HQ Aviation showroom' },
      { id: 'sg2',  url: '/assets/images/facility/hq-aviation-robinsons.jpg', alt: 'Fleet on the apron' },
      { id: 'sg3',  url: '/assets/images/facility/hq-0477.jpg',               alt: 'Helicopter instruments' },
      { id: 'sg4',  url: '/assets/images/facility/hq-0391.jpg',               alt: 'Engineering workshop' },
      { id: 'sg5',  url: '/assets/images/facility/hq-0745.jpg',               alt: 'Helicopter on apron' },
      { id: 'sg6',  url: '/assets/images/facility/hq-0354.jpg',               alt: 'Pre-flight checks' },
      { id: 'sg7',  url: '/assets/images/facility/hq-0696.jpg',               alt: 'Cockpit detail' },
      { id: 'sg8',  url: '/assets/images/facility/hq-0167.jpg',               alt: 'Hangar interior' },
      { id: 'sg9',  url: '/assets/images/facility/hq-0089.jpg',               alt: 'Rotor detail' },
      { id: 'sg10', url: '/assets/images/facility/hq-0035.jpg',               alt: 'Maintenance inspection' },
    ],
  },
  {
    id: 'home-sales-mobile-carousel',
    page: 'home',
    name: 'Sales — Mobile Carousel',
    hint: 'Mobile-only scrolling photo carousel at the top of the Sales section',
    type: 'gallery',
    viewport: 'mobile',
    images: [
      { id: 'sc1', url: '/assets/images/facility/main-sales-pic.jpg',        alt: 'HQ Aviation showroom' },
      { id: 'sc2', url: '/assets/images/facility/hq-aviation-robinsons.jpg', alt: 'Fleet on the apron' },
      { id: 'sc3', url: '/assets/images/facility/hq-0477.jpg',               alt: 'Helicopter instruments' },
      { id: 'sc4', url: '/assets/images/facility/hq-0391.jpg',               alt: 'Engineering workshop' },
      { id: 'sc5', url: '/assets/images/facility/hq-0745.jpg',               alt: 'Helicopter on apron' },
      { id: 'sc6', url: '/assets/images/facility/hq-0354.jpg',               alt: 'Pre-flight checks' },
      { id: 'sc7', url: '/assets/images/facility/hq-0696.jpg',               alt: 'Cockpit detail' },
      { id: 'sc8', url: '/assets/images/facility/hq-0167.jpg',               alt: 'Hangar interior' },
    ],
  },
  {
    id: 'home-parallax-flying',
    page: 'home',
    name: 'Parallax — Flying Section',
    hint: 'Full-screen background image behind the "Flying" parallax divider',
    type: 'single',
    viewport: 'both',
    images: [
      { id: 'pf1', url: '/assets/images/gallery/flying/flying-.jpg', alt: 'Helicopter flying' },
    ],
  },
  {
    id: 'home-parallax-sales',
    page: 'home',
    name: 'Parallax — Sales Section',
    hint: 'Full-screen background image behind the "Sales" parallax divider',
    type: 'single',
    viewport: 'both',
    images: [
      { id: 'ps1', url: '/assets/images/facility/fleet-lineup-sunset.jpg', alt: 'Fleet at sunset' },
    ],
  },
  {
    id: 'home-parallax-maintenance',
    page: 'home',
    name: 'Parallax — Maintenance Section',
    hint: 'Full-screen background image behind the "Maintenance" parallax divider',
    type: 'single',
    viewport: 'both',
    images: [
      { id: 'pm1', url: '/assets/images/facility/maintenance-.jpg', alt: 'Maintenance facility' },
    ],
  },
  {
    id: 'home-parallax-contact',
    page: 'home',
    name: 'Parallax — Contact Section',
    hint: 'Full-screen background image behind the "Contact & Find Us" parallax divider',
    type: 'single',
    viewport: 'both',
    images: [
      { id: 'pc1', url: '/assets/images/facility/hq-0035.jpg', alt: 'HQ Aviation facility' },
    ],
  },

  {
    id: 'home-training-specialist',
    page: 'home',
    name: 'Training — Specialist Services Cards',
    hint: 'One image per specialist service card at the bottom of the Training section (SuperYacht Ops, Pilot Provisioning, Advanced Training, Aircraft Consulting)',
    type: 'carousel',
    viewport: 'both',
    slideLabels: ['SuperYacht Ops', 'Pilot Provisioning', 'Advanced Training', 'Aircraft Consulting'],
    images: [
      { id: 'ts1', url: '/assets/images/lifestyle/superyacht-ops.jpg',       alt: 'Superyacht operations' },
      { id: 'ts2', url: '/assets/images/gallery/flying/flying--1.jpg',       alt: 'Pilot provisioning' },
      { id: 'ts3', url: '/assets/images/gallery/flying/flying-.jpg',         alt: 'Advanced training' },
      { id: 'ts4', url: '/assets/images/facility/hq-0354.jpg',               alt: 'Aircraft consulting' },
    ],
  },
  {
    id: 'home-clubhouse-gallery',
    page: 'home',
    name: 'Clubhouse — Desktop Photo Grid',
    hint: 'CSS photo grid in the Clubhouse section (desktop). Fixed 9-slot layout: wide, square, square, tall, square, wide, square, square, wide.',
    type: 'gallery',
    viewport: 'desktop',
    images: [
      { id: 'cg1', url: '/assets/images/facility/hq-0345.jpg',   alt: 'The clubhouse lounge' },
      { id: 'cg2', url: '/assets/images/facility/hq-0354.jpg',   alt: 'Globe on the clubhouse desk' },
      { id: 'cg3', url: '/assets/images/facility/hq-0053.jpg',   alt: 'Helmet light and framed photos' },
      { id: 'cg4', url: '/assets/images/facility/hq-0391.jpg',   alt: 'Captain Q expedition photo on the wall' },
      { id: 'cg5', url: '/assets/images/facility/hq-0477.jpg',   alt: 'Helicopter compass instrument' },
      { id: 'cg6', url: '/assets/images/facility/hq-0300.jpg',   alt: 'R66 Turbine cockpit instruments' },
      { id: 'cg7', url: '/assets/images/facility/hq-0388.jpg',   alt: "Air Pilot's Manual on vintage trunk" },
      { id: 'cg8', url: '/assets/images/facility/hq-0696.jpg',   alt: 'Captain Q flying' },
      { id: 'cg9', url: '/assets/images/facility/hq-0153-3.jpg', alt: 'Helicopters on the airfield' },
    ],
  },
  {
    id: 'home-sales-aircraft',
    page: 'home',
    name: 'Sales — New Aircraft Model Images',
    hint: 'Cutout image for each new helicopter model in the Sales section (R88, R66 Turbine, R44 Raven II, R22 Beta II)',
    type: 'carousel',
    viewport: 'both',
    slideLabels: ['R88', 'R66 Turbine', 'R44 Raven II', 'R22 Beta II'],
    images: [
      { id: 'na1', url: '/assets/images/new-aircraft/r88/r88-jellybean-left.png',              alt: 'Robinson R88' },
      { id: 'na2', url: '/assets/images/new-aircraft/r66/blue-r66-palo-verde-front-v4.png',    alt: 'Robinson R66 Turbine' },
      { id: 'na3', url: '/assets/images/new-aircraft/r44/raven-ii-front-alpha.png',            alt: 'Robinson R44 Raven II' },
      { id: 'na4', url: '/assets/images/new-aircraft/r22/r22-red-volcano-front-alpha-v3.png', alt: 'Robinson R22 Beta II' },
    ],
  },

  // ─── ABOUT US PAGE ─────────────────────────────────────────────────────────
  {
    id: 'about-founder',
    page: 'about',
    name: 'Founder Portrait',
    hint: 'Captain Quentin Smith portrait in the "Captain Q" section',
    type: 'single',
    images: [
      { id: 's11', url: '/assets/images/team/world-helicopter-champion-quentin-smith.webp', alt: 'Captain Quentin Smith' },
    ],
  },

  // ─── DISCOVERY FLIGHT PAGE ────────────────────────────────────────────────
  {
    id: 'discovery-hero',
    page: 'discovery',
    name: 'Hero Background',
    hint: 'Full-screen background image at the very top of the Discovery Flight page',
    type: 'single',
    images: [
      { id: 'dh1', url: '/assets/images/gallery/carousel/rotating8.jpg', alt: 'Helicopter in flight' },
    ],
  },
  {
    id: 'discovery-aircraft',
    page: 'discovery',
    name: 'Aircraft Booking Cards',
    hint: 'One image per aircraft booking card — R22, R44, R66',
    type: 'cards',
    slideLabels: ['Robinson R22', 'Robinson R44', 'Robinson R66'],
    images: [
      { id: 'da1', url: '/assets/images/new-aircraft/r22/r22-red-volcano-front-alpha-v3.png', alt: 'Robinson R22' },
      { id: 'da2', url: '/assets/images/new-aircraft/r44/raven-ii-front-alpha.png',            alt: 'Robinson R44' },
      { id: 'da3', url: '/assets/images/new-aircraft/r66/blue-r66-palo-verde-front-v4.png',   alt: 'Robinson R66' },
    ],
  },
  {
    id: 'discovery-instructor',
    page: 'discovery',
    name: 'Lead Instructor Portrait',
    hint: 'Portrait photo in the "Your Instructor" section',
    type: 'single',
    images: [
      { id: 'di1', url: '/assets/images/team/quentin-smith-profile-picture.jpg', alt: 'Quentin Smith — Lead Instructor' },
    ],
  },

  // ─── SELF-FLY HIRE PAGE ───────────────────────────────────────────────────
  {
    id: 'sfh-hero',
    page: 'sfh',
    name: 'Hero Background',
    hint: 'Full-screen background image at the top of the Self-Fly Hire page',
    type: 'single',
    images: [
      { id: 'sh1', url: '/assets/images/gallery/carousel/rotating1.jpg', alt: 'Helicopter in flight' },
    ],
  },
  {
    id: 'sfh-fleet',
    page: 'sfh',
    name: 'Fleet Aircraft Images',
    hint: 'One aircraft image per fleet tab — R22, R44 Raven II, R66 Turbine',
    type: 'cards',
    slideLabels: ['Robinson R22', 'Robinson R44 Raven II', 'Robinson R66 Turbine'],
    images: [
      { id: 'sf1', url: '/assets/images/fleet/r22-g-ulze.png',  alt: 'Robinson R22' },
      { id: 'sf2', url: '/assets/images/fleet/r44-g-mxpi.png',  alt: 'Robinson R44 Raven II' },
      { id: 'sf3', url: '/assets/images/fleet/r66-g-tlmi.png',  alt: 'Robinson R66 Turbine' },
    ],
  },
  {
    id: 'sfh-intro',
    page: 'sfh',
    name: 'Intro Section Image',
    hint: 'Fleet photo beside the introduction paragraph',
    type: 'single',
    images: [
      { id: 'si1', url: '/assets/images/facility/fleet-lineup.jpg', alt: 'HQ Aviation helicopter fleet' },
    ],
  },
  {
    id: 'sfh-destinations',
    page: 'sfh',
    name: 'Destination Photos',
    hint: 'Gallery of destination images — cycle by index across all destination cards',
    type: 'gallery',
    images: [
      { id: 'sd1',  url: '/assets/images/gallery/carousel/rotating4.jpg',  alt: 'Goodwood' },
      { id: 'sd2',  url: '/assets/images/gallery/carousel/rotating5.jpg',  alt: 'Cotswolds' },
      { id: 'sd3',  url: '/assets/images/gallery/carousel/rotating2.jpg',  alt: 'Cambridge' },
      { id: 'sd4',  url: '/assets/images/gallery/carousel/rotating3.jpg',  alt: 'Oxford' },
      { id: 'sd5',  url: '/assets/images/gallery/carousel/rotating6.jpg',  alt: 'Lake District' },
      { id: 'sd6',  url: '/assets/images/gallery/carousel/rotating7.jpg',  alt: 'Channel Islands' },
      { id: 'sd7',  url: '/assets/images/gallery/carousel/rotating8.jpg',  alt: 'St Andrews' },
      { id: 'sd8',  url: '/assets/images/gallery/carousel/rotating9.jpg',  alt: 'Brighton' },
      { id: 'sd9',  url: '/assets/images/gallery/carousel/rotating10.jpg', alt: 'Bath' },
      { id: 'sd10', url: '/assets/images/gallery/carousel/rotating2.jpg',  alt: 'Cardiff' },
      { id: 'sd11', url: '/assets/images/gallery/carousel/rotating3.jpg',  alt: 'Edinburgh' },
      { id: 'sd12', url: '/assets/images/gallery/carousel/rotating4.jpg',  alt: 'Silverstone' },
      { id: 'sd13', url: '/assets/images/gallery/carousel/rotating5.jpg',  alt: 'Le Touquet' },
      { id: 'sd14', url: '/assets/images/gallery/carousel/rotating6.jpg',  alt: 'Paris' },
      { id: 'sd15', url: '/assets/images/gallery/carousel/rotating7.jpg',  alt: 'Deauville' },
      { id: 'sd16', url: '/assets/images/gallery/carousel/rotating8.jpg',  alt: 'Chantilly' },
      { id: 'sd17', url: '/assets/images/gallery/carousel/rotating9.jpg',  alt: 'Reims' },
      { id: 'sd18', url: '/assets/images/gallery/carousel/rotating10.jpg', alt: 'Bruges' },
      { id: 'sd19', url: '/assets/images/gallery/carousel/rotating2.jpg',  alt: 'Amsterdam' },
      { id: 'sd20', url: '/assets/images/gallery/carousel/rotating3.jpg',  alt: 'Brussels' },
    ],
  },
  {
    id: 'sfh-cta',
    page: 'sfh',
    name: 'Call-to-Action Image',
    hint: 'Background image in the "Book Your First Flight" CTA section at the bottom',
    type: 'single',
    images: [
      { id: 'sc1', url: '/assets/images/gallery/carousel/rotating8.jpg', alt: 'Helicopter in flight' },
    ],
  },

  // ─── AIRCRAFT SALES PAGE ──────────────────────────────────────────────────
  {
    id: 'sales-aircraft-hero',
    page: 'sales',
    name: 'Aircraft Hero Images',
    hint: 'Large atmospheric photo per model — R88, R66, R44, R22. Shown in the hero when that model is selected.',
    type: 'cards',
    slideLabels: ['R88', 'R66', 'R44', 'R22'],
    images: [
      { id: 'sah1', url: '/assets/images/new-aircraft/r88/rhc-r88-3-spotlights-left-side-atmospheric-effect-21794_2.jpg',  alt: 'Robinson R88' },
      { id: 'sah2', url: '/assets/images/new-aircraft/r66/rhc-r66-nxg-riviera-center-spotlight-vertical-format-14184-2.jpg', alt: 'Robinson R66' },
      { id: 'sah3', url: '/assets/images/new-aircraft/r44/r44blueprint.jpg',                                                   alt: 'Robinson R44' },
      { id: 'sah4', url: '/assets/images/new-aircraft/r22/r22blueprint.jpg',                                                   alt: 'Robinson R22' },
    ],
  },
  {
    id: 'sales-aircraft-cutout',
    page: 'sales',
    name: 'Aircraft Cutout PNGs',
    hint: 'Transparent cutout PNG per model — R88, R66, R44, R22. Shown in the model selector.',
    type: 'cards',
    slideLabels: ['R88 Cutout', 'R66 Cutout', 'R44 Cutout', 'R22 Cutout'],
    images: [
      { id: 'sac1', url: '/assets/images/new-aircraft/r88/r88-jellybean-left.png',              alt: 'R88 transparent cutout' },
      { id: 'sac2', url: '/assets/images/new-aircraft/r66/blue-r66-palo-verde-front-v4.png',    alt: 'R66 transparent cutout' },
      { id: 'sac3', url: '/assets/images/new-aircraft/r44/raven-ii-front-alpha.png',            alt: 'R44 transparent cutout' },
      { id: 'sac4', url: '/assets/images/new-aircraft/r22/r22-red-volcano-front-alpha-v3.png', alt: 'R22 transparent cutout' },
    ],
  },
  {
    id: 'sales-used',
    page: 'sales',
    name: 'Used Aircraft Photos',
    hint: 'One photo per used aircraft listing (in order)',
    type: 'gallery',
    images: [
      { id: 'su1', url: '/assets/images/used-aircraft/r66/r66-turbine-ghkcc.jpg', alt: 'Used R66 Turbine' },
      { id: 'su2', url: '/assets/images/new-aircraft/r44/r44blueprint.jpg',        alt: 'Used R44 Raven II' },
      { id: 'su3', url: '/assets/images/used-aircraft/r66/chris-r66-alps.jpg',    alt: 'Used R66 Turbine (Alps)' },
    ],
  },
  // ─── HOME PAGE — EXPEDITIONS SECTION ─────────────────────────────────────
  {
    id: 'home-exped-gallery-arctic',
    page: 'home',
    name: 'Expeditions — Arctic Gallery',
    hint: 'Photos shown in the expanded gallery when Arctic is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'aeg1', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'Arctic expedition' },
      { id: 'aeg2', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Six helicopters at North Pole' },
      { id: 'aeg3', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
      { id: 'aeg4', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
    ],
  },
  {
    id: 'home-exped-gallery-iceland',
    page: 'home',
    name: 'Expeditions — Iceland Gallery',
    hint: 'Photos shown in the expanded gallery when Iceland is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'ieg1', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'ieg2', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
      { id: 'ieg3', url: '/assets/images/expeditions/south-pole-by-helicopter-quentin-smith.webp', alt: 'South Pole expedition' },
      { id: 'ieg4', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
    ],
  },
  {
    id: 'home-exped-gallery-morocco',
    page: 'home',
    name: 'Expeditions — Morocco Gallery',
    hint: 'Photos shown in the expanded gallery when Morocco is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'meg1', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
      { id: 'meg2', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'meg3', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'North Pole' },
      { id: 'meg4', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Six helicopters at North Pole' },
    ],
  },
  {
    id: 'home-exped-gallery-norway',
    page: 'home',
    name: 'Expeditions — Norway Gallery',
    hint: 'Photos shown in the expanded gallery when Norway is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'neg1', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Six helicopters at North Pole' },
      { id: 'neg2', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'North Pole' },
      { id: 'neg3', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'neg4', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
    ],
  },
  {
    id: 'home-exped-gallery-alps',
    page: 'home',
    name: 'Expeditions — Alps Gallery',
    hint: 'Photos shown in the expanded gallery when Alps is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'alg1', url: '/assets/images/expeditions/south-pole-by-helicopter-quentin-smith.webp', alt: 'South Pole expedition' },
      { id: 'alg2', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
      { id: 'alg3', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'alg4', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Six helicopters at North Pole' },
    ],
  },
  {
    id: 'home-exped-gallery-greenland',
    page: 'home',
    name: 'Expeditions — Greenland Gallery',
    hint: 'Photos shown in the expanded gallery when Greenland is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'geg1', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
      { id: 'geg2', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'North Pole' },
      { id: 'geg3', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Six helicopters at North Pole' },
      { id: 'geg4', url: '/assets/images/expeditions/south-pole-by-helicopter-quentin-smith.webp', alt: 'South Pole expedition' },
    ],
  },
  {
    id: 'home-exped-gallery-bahamas',
    page: 'home',
    name: 'Expeditions — Bahamas Gallery',
    hint: 'Photos shown in the expanded gallery when Bahamas is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'beg1', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'beg2', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
      { id: 'beg3', url: '/assets/images/expeditions/south-pole-by-helicopter-quentin-smith.webp', alt: 'South Pole expedition' },
      { id: 'beg4', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
    ],
  },
  {
    id: 'home-exped-gallery-costa-rica',
    page: 'home',
    name: 'Expeditions — Costa Rica Gallery',
    hint: 'Photos shown in the expanded gallery when Costa Rica is selected',
    type: 'gallery',
    viewport: 'both',
    images: [
      { id: 'crg1', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Captain Q expedition' },
      { id: 'crg2', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Channel crossing' },
      { id: 'crg3', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'North Pole' },
      { id: 'crg4', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Antarctica' },
    ],
  },

  {
    id: 'home-exped-barcode-thumbs',
    page: 'home',
    name: 'Expeditions — Destination Thumbnails',
    hint: 'Thumbnail shown on each destination barcode card in the Expeditions section',
    type: 'cards',
    viewport: 'both',
    slideLabels: ['Arctic', 'Iceland', 'Morocco', 'Norway', 'Alps', 'Greenland', 'Bahamas', 'Costa Rica'],
    images: [
      { id: 'eb1', url: '/assets/images/expeditions/north-pole.jpg',                              alt: 'Arctic' },
      { id: 'eb2', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Iceland' },
      { id: 'eb3', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Morocco' },
      { id: 'eb4', url: '/assets/images/expeditions/six-helis-in-North-Pole.jpg',                 alt: 'Norway' },
      { id: 'eb5', url: '/assets/images/expeditions/south-pole-by-helicopter-quentin-smith.webp', alt: 'Alps' },
      { id: 'eb6', url: '/assets/images/expeditions/antartica.jpg',                               alt: 'Greenland' },
      { id: 'eb7', url: '/assets/images/expeditions/channel.jpg',                                 alt: 'Bahamas' },
      { id: 'eb8', url: '/assets/images/expeditions/helicopter-expeditions-quentin-smith.webp',   alt: 'Costa Rica' },
    ],
  },

  {
    id: 'sales-paint',
    page: 'sales',
    name: 'Paint Scheme Gallery',
    hint: 'One image per paint scheme — Classic White, Palo Verde, Riviera Blue, Corporate Black, Racing Red, Bespoke',
    type: 'cards',
    slideLabels: ['Classic White', 'Palo Verde', 'Riviera Blue', 'Corporate Black', 'Racing Red', 'Bespoke'],
    images: [
      { id: 'sp1', url: '/assets/images/new-aircraft/r66/rhc-r66-nxg-pv-left-side-wide-view-13611.jpg', alt: 'Classic White' },
      { id: 'sp2', url: '/assets/images/new-aircraft/r66/blue-r66-palo-verde-front-v4.png',             alt: 'Palo Verde' },
      { id: 'sp3', url: '/assets/images/new-aircraft/r66/copy-of-r66-riviera-front-v2.png',             alt: 'Riviera Blue' },
      { id: 'sp4', url: '/assets/images/new-aircraft/r88/rhc-r88-right-side-view-dark-21823_2.jpg',     alt: 'Corporate Black' },
      { id: 'sp5', url: '/assets/images/new-aircraft/r22/r22-red-volcano-front-alpha-v3.png',           alt: 'Racing Red' },
      { id: 'sp6', url: '/assets/images/facility/hq-aviation-robinsons.jpg',                            alt: 'Bespoke Design' },
    ],
  },
];

// Convenient lookups
export const SECTION_MAP = Object.fromEntries(SECTIONS.map((s) => [s.id, s]));

export const SECTIONS_BY_PAGE = SECTIONS.reduce((acc, s) => {
  (acc[s.page] = acc[s.page] || []).push(s);
  return acc;
}, {});

export const PAGE_LABELS = {
  home:        'Home Page',
  training:    'Training Page',
  maintenance: 'Maintenance Page',
  expeditions: 'Expeditions Page',
  about:       'About Us Page',
  discovery:   'Discovery Flight Page',
  sfh:         'Self-Fly Hire Page',
  sales:       'Aircraft Sales Page',
};
